version: 2

models:
  - name: sat_app
    description: satellite for application data source
    columns:
      - name: HK_APP
        description: application hashed key
      - name: HDIFF_APP
        description: hashed difference key for application details
      - name: APP_NAME
        description: name of the application
      - name: APP_DESCRIPTION
        description: application description
      - name: APP_IMAGE_URL
        description: Cloudinary url to the application logo
      - name: SEARCH_TERM
        description: support connecting to specific expense
      - name: NET_SUITE_SEARCH_TERM
        description: support connecting to specific expense
      - name: APP_URL
        description: app url
      - name: APP_PRICING_URL
        description: url to the application pricing page
      - name: CATEGORY
        description: app category
      - name: VENDOR
        description: vendor of the application
      - name: IND_INTEGRATION
        description: integration to torii exist
      - name: IND_PUBLIC
        description: apps the are familiar but not followed , will not show to user
      - name: IND_CUSTOM
        description: depricated, historicly used to handle custom applications not from the list, if idOrg exist will contain true
      - name: IND_ARCHIVED
        description: for duplicate apps app get archived ?
      - name: RECORD_SOURCE
        description: is defined as a constant by prefixing the constant value with !. the record table source
      - name: LOAD_DATE
        description: is defined as a calculated column using a function. Here we are synthetically creating a LOAD_DATE for the purposes of simulating a transaction feed
      - name: EFFECTIVE_FROM
        description: is our business effective date for a given record, and it makes sense to derive this from the TRANSACTION_DATE
  - name: sat_user
    description: satellite for user data source
    columns:
      - name: HK_USER
        description: hashed key of the user id
      - name: HDIFF_USER_DETAILS
        description: hashed difference key for user details
      - name: HDIFF_USER_OFF_BOARD
        description: hashed diffrence key for user off boarding details
      - name: USER_NAME
        description: first_name + last_name
      - name: USER_STATUS
        description: status of the user in the system
      - name: LIFE_CYCLE_STATUS
        description: life cycle status of the user. can be 3 active => offboarding => offboarded
      - name: USER_EMAIL
        description: email of the user
      - name: USER_CANONICAL_EMAIL
        description: email of the user without special characters, like . + , etc...
      - name: USER_PHOTO_URL
        description: workflow action started off-boarding for the user
      - name: IND_RESTRICTED_TORII_ADMIN
        description: only for SE , indication permission to view other organization data restricted to a list
      - name: IND_DELETED_INIDENTITY_SOURCES
        description: indication if user deleted on identity app source. like gsuite for example, if so user can be recommended to deletion and start his offboarding
      - name: IND_USER_EXTERNAL
        description: users that their domain not in recognized domain, in org domain table list by the org
      - name: IND_TORII_ADMIN
        description: only for R&D ,indication permission to view other organization data
      - name: DT_IDENTITY_SOURCES_DELETION
        description: time when user deleted on identity app source. like gsuite for example, if so user can be recommended to deletion and start his offboarding
      - name: DT_LAST_SEEN_PRODUCT_UPDATES
        description: last time saw product updates by torii new features
      - name: DT_OFF_BOARD_START
        description: off-boarding process started time
      - name: DT_OFF_BOARD_END
        description: off-boarding process ending time
      - name: RECORD_SOURCE
        description: is defined as a constant by prefixing the constant value with !. the record table source
      - name: LOAD_DATE
        description: is defined as a calculated column using a function. Here we are synthetically creating a LOAD_DATE for the purposes of simulating a transaction feed
      - name: EFFECTIVE_FROM
        description: is our business effective date for a given record, and it makes sense to derive this from the TRANSACTION_DATE
  - name: sat_org
    description: satellite for org data source
    columns:
      - name: HK_ORG
        description: hashed org key
      - name: HDIFF_ORG
        description: hashed diffrence org value
      - name: ORG_DOMAIN
        description: company site domain
      - name: COMPANY_NAME
        description: company name
      - name: ORG_NICK_NAME
        description: company nick name, in catalog use
      - name: ORG_EMAIL_ALIAS
        description: the signature name of an email sent by Torii, usually IT, deifned by the customer
      - name: ORG_LOGO_URL
        description: company url of logo
      - name: EXTENSION_MODE
        description: defines if Torii collect data by extension, can be authenticated or unauthenticated
      - name: DEFAULT_CURRENCY
        description: the defualt expenses currency of the customer
      - name: USER_LIFE_CYCLE_CONFIG
        description: which service (gsuite, google,etc...) defines user onboarding/offboarding
      - name: APP_NOT_IN_USER_PERIOD
        description: number of days defines an app not in use, by the customer
      - name: DT_TRIAL_END
        description: date of when trial will end, after which customer will not be able to login
      - name: DT_PAID_PLAN
        description: date of when paied plan will end, after which customer will not be able to login, in contrast to isDisabled workflow and other features will continute to run
      - name: INACTIVITY_TIMEOUT
        description: monitor time if user didn't touched torii GUI the session will timeout
      - name: IND_DEMO
        description: indication to a demo customer account
      - name: IND_WHITE_LABEL
        description: indication for organization to show their own logo and not use Torii's logo in internal mails
      - name: IND_DISABLED
        description: indication to a disabled customer account, if disabled customer will not be able to login
      - name: RECORD_SOURCE
        description: is defined as a constant by prefixing the constant value with !. the record table source
      - name: LOAD_DATE
        description: is defined as a calculated column using a function. Here we are synthetically creating a LOAD_DATE for the purposes of simulating a transaction feed
      - name: EFFECTIVE_FROM
        description: is our business effective date for a given record, and it makes sense to derive this from the TRANSACTION_DATE
      - name: START_DATE
        description: is our business start date for a given record, and it makes sense to derive this from the entity recorded start date will remain constant
  - name: sat_role
    description: satellite for role data source
    columns:
      - name: HK_ROLE
        description: hashed key role
      - name: HDIFF_ROLE
        description: hashed diffrence key role details
      - name: ROLE_NAME
        description: name of the role
      - name: ROLE_DESCRIPTION
        description: description of the role
      - name: SYSTEMKEY
        description: the role description key
      - name: IND_ADMIN
        description: indication if the role is an admin permissions
      - name: IND_INTERNAL
        description: indication if the role is internal role for torii
      - name: IND_DELETED
        description: indication if the role is deleted
      - name: EFFECTIVE_FROM
        description: An effectivity date. Usually called EFFECTIVE_FROM, this column is the business effective date of a Satellite record. It records that a record is valid from a specific point in time. If a customer changes their name, then the record with their 'old' name should no longer be valid, and it will no longer have the most recent EFFECTIVE_FROM value.
      - name: LOAD_DATE
        description: Load date (src_ldts)-A load date or load date timestamp. This identifies when the record was first loaded into the database.
      - name: RECORD_SOURCE
        description: Record Source (src_source)-The source for the record. This can be a code which is assigned to a source name in an external lookup table, or a string directly naming the source system. (i.e. 1 from the staging section, which is the code for stg_customer)