version: 2

sources:
  - name: raw_stage_torii
    description: 'torii operational source data'
    database: STAGE_FIVETRAN
    schema: RAW_TORII
    tables:
      - name: org
        description: 'torii org table is for all the customers list tables'
